#spring:
#  application:
#    name: sojson-weather-eureka-client-zuul
#
#server:
#  port: 8087
#
#eureka:
#  port: 8080
#  instance:
#    hostname: localhost
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.port}/eureka/
#
#zuul:
#  max:
#    host:
#      connections: 500
#  host:
#    socket-timeout-millis: 6000
#    connect-timeout-millis: 6000
#  routes:
#      city:
#        path: /city/**
#        server-id: sojson-weather-city-eureka
#
#
#      data:
#        path: /data/**
#        server-id: sojson-weather-data-data-eureka
#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#  eureka:
#    enabled: false